geekshop/authapp/urls.py
from django.urls import path
from .views import login, logout, register, edit

app_name = 'authapp'

urlpatterns = [
    path('login', login, name="login"),
    path('logout', logout, name="logout"),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
]

geekshop/basketapp/urls.py
from django.urls import path
from .views import basket_add, basket_remove, basket

app_name = 'basketapp'

urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, contacts
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('contacts/', contacts, name="contacts"),
    path('products/', include('mainapp.urls', namespace="products")),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace="auth")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/urls.py
from django.urls import path
from .views import products

app_name = 'products'

urlpatterns = [
    path('', products, name="index"),
    path('category/<int:pk>/', products, name='category'),

]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)

    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name or f'Category with id - {self.pk}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        verbose_name='категория',
        on_delete=models.CASCADE
    )
    name = models.CharField(
        verbose_name='имя продукта',
        max_length=128,
    )
    image = models.ImageField(
        verbose_name='изображение',
        upload_to='product_images',
        blank=True,
    )
    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=100,
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество товара на складе',
        default=0,
    )

    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name or f'Product with id - {self.pk}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory
from basketapp.models import Basket


def products(request, pk=None):
    title = 'продукты/каталог'
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)

    links_menu = ProductCategory.objects.all()
    products = Product.objects.all().order_by('price')

    if pk is not None:
        if pk == 0:
            products = Product.objects.all().order_by('price')
            category = {'name': 'все'}
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk).order_by('price')

        context = {
            'title': title,
            'links_menu': links_menu,
            'products': products,
            'category': category,
        }
        return render(request=request, template_name='mainapp/products.html', context=context)

    same_products = Product.objects.all()[3:5]

    context = {
        'title': title,
        'links_menu': links_menu,
        'same_products': same_products,
        'products': products,
        'basket': basket,
    }
    return render(request=request, template_name='mainapp/products.html', context=context)

geekshop/mainapp/templates/mainapp/products.html
{% extends 'geekshop/base.html' %}
{% load static %}

{% block styles %}
        <link rel="stylesheet" type="text/css" href="{% static 'mainapp/style.css' %}">
{% endblock %}


{% block content %}
<div class="hero-white">
    {% include 'geekshop/includes/inc_main_menu.html' %}
</div>
    {% include 'mainapp/includes/inc_category_menu.html' %}
<div class="details">


    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/static/geekshop/img/slider1.jpg">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/static/geekshop/img/controll.jpg" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/static/geekshop/img/controll1.jpg" alt="">
                        <div class="text"></div>
                    </a>
                </div>
                <div class="block">
                    <a href="#"><img src="/static/geekshop/img/controll2.jpg" alt="">
                        <div class="text"></div>
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">Отличный стул</h3>
            <h3 class="red">горячее предложение</h3>
            <h3 class="red">только до {% now "M Y" %}</h3>
            <p class="price"> 2585.9 <span>руб</span></p>
            <a href="#" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                <p>Расположитесь комфортно.</p>
                <p>Отличное качество материалов
                    позволит вам это.</p>
                <p>Различные цвета</p>
                <p>высочайший уровень
                    эргономики и прочность.</p>
            </div>
        </div>
    </div>
	<div class="featured">
			<h2>
			  Категория: "{{ category.name|title }}"
			</h2>
			<div class="featured-menu">
				<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				{% for product in products %}
					<div class="block">
						<a href="{% url 'basket:add' product.pk %}"><img src="/media/{{product.image}}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{product.name}}</h4>
								<p>{{product.short_desc}}. </p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/geekshop/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="/media/{{product.image}}" alt="">
							<div class="text">
								<img src="img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					{% for prod in same_products %}
					<div class="block">
						<a href="#"><img src="/media/{{prod.image}}" alt="">
							<div class="text">
								<img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
								<h4>{{prod.name}}</h4>
								<p>{{prod.description}}</p>
							</div>
						</a>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
{% endblock %}